import {
  Finding,
  IssueSummary,
  SavingsMetrics,
  DashboardStats,
  ActivityLogItem,
  Notification,
} from '@/types';

export const mockFindings: Finding[] = [
  {
    id: '1',
    status: 'new',
    vendor: 'AWS',
    issue: 'Invoice #789 charged twice',
    amount: 1847,
    confidence: 100,
    confidenceLevel: 'certain',
    type: 'duplicate',
    dateFound: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
  },
  {
    id: '2',
    status: 'new',
    vendor: 'Google Workspace',
    issue: 'Duplicate charge 3 days apart',
    amount: 450,
    confidence: 95,
    confidenceLevel: 'certain',
    type: 'duplicate',
    dateFound: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: '3',
    status: 'new',
    vendor: 'Zoom',
    issue: '42 unused licenses',
    amount: 840,
    confidence: 100,
    confidenceLevel: 'certain',
    type: 'subscription',
    dateFound: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: '4',
    status: 'new',
    vendor: 'Slack',
    issue: '2 separate workspaces',
    amount: 500,
    confidence: 90,
    confidenceLevel: 'likely',
    type: 'subscription',
    dateFound: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: '5',
    status: 'new',
    vendor: 'Monday.com',
    issue: '34% price increase',
    amount: 340,
    confidence: 100,
    confidenceLevel: 'certain',
    type: 'price_increase',
    dateFound: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: '6',
    status: 'new',
    vendor: 'Stripe',
    issue: 'Invoice #1234 charged 3 times',
    amount: 1200,
    confidence: 98,
    confidenceLevel: 'certain',
    type: 'duplicate',
    dateFound: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: '7',
    status: 'new',
    vendor: 'Adobe Creative Cloud',
    issue: '15 unused seats',
    amount: 600,
    confidence: 100,
    confidenceLevel: 'certain',
    type: 'subscription',
    dateFound: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: '8',
    status: 'new',
    vendor: 'Salesforce',
    issue: '22% price increase since January',
    amount: 780,
    confidence: 100,
    confidenceLevel: 'certain',
    type: 'price_increase',
    dateFound: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: '9',
    status: 'in_progress',
    vendor: 'Notion',
    issue: 'Duplicate workspace billing',
    amount: 320,
    confidence: 85,
    confidenceLevel: 'likely',
    type: 'subscription',
    dateFound: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: '10',
    status: 'new',
    vendor: 'Dropbox Business',
    issue: '28 inactive users still billed',
    amount: 560,
    confidence: 95,
    confidenceLevel: 'certain',
    type: 'subscription',
    dateFound: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
];

export const mockIssueSummaries: IssueSummary[] = [
  {
    type: 'duplicate',
    totalAmount: 3200,
    count: 7,
    example: 'AWS invoice #1234 charged 3 times',
    color: 'red',
    icon: '',
    label: 'Duplicate Charges',
  },
  {
    type: 'subscription',
    totalAmount: 2100,
    count: 12,
    example: 'Paying for 50 Zoom seats, using 8',
    color: 'yellow',
    icon: '',
    label: 'Zombie Subscriptions',
  },
  {
    type: 'price_increase',
    totalAmount: 1400,
    count: 5,
    example: 'Salesforce up 22% since January',
    color: 'orange',
    icon: '',
    label: 'Price Increases',
  },
];

export const mockSavings: SavingsMetrics = {
  thisMonth: 4200,
  thisYear: 18400,
  total: 23700,
};

export const mockDashboardStats: DashboardStats = {
  totalWaste: 12847,
  lastScanned: new Date(Date.now() - 2 * 60 * 60 * 1000),
  invoicesAnalyzed: 1247,
  issuesFound: 94,
  scansUsed: 3,
  scansLimit: 10,
};

export const mockActivityLog: ActivityLogItem[] = [
  {
    id: '1',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    message: 'Scanned 47 new emails',
    type: 'scan',
  },
  {
    id: '2',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    message: 'Found duplicate invoice from Microsoft',
    type: 'finding',
  },
  {
    id: '3',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    message: 'Identified $800 in unused subscriptions',
    type: 'finding',
  },
  {
    id: '4',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    message: 'Price increase detected for Notion',
    type: 'alert',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'new',
    icon: 'NEW',
    message: 'New: Found duplicate Stripe charge 2 hours ago',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: '2',
    type: 'trend',
    icon: 'TRD',
    message: 'Trend: AWS spending up 40% this month',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: '3',
    type: 'reminder',
    icon: 'REM',
    message: 'Reminder: Cancel Unused Adobe subscription (saving $600/year)',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: '4',
    type: 'tip',
    icon: 'TIP',
    message: 'Tip: 3 vendors haven\'t been reviewed in 6 months',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
];
